apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indic-nlp-ingress
  namespace: indic-nlp
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: indic-nlp-service
            port:
              number: 80
