apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sentiment-api-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: api
        image: your-docker-username/sentiment-api:latest   # ← change this
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 300m
            memory: 800Mi
          limits:
            cpu: 800m
            memory: 1.5Gi
        env:
        - name: REDIS_HOST
          value: redis
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 60s}
      - setWeight: 100