# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: indic-nlp-service
  namespace: indic-nlp
  labels:
    app: indic-nlp
spec:
  selector:
    app: indic-nlp
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP